version: '3.8'
name: 'friendship_api_development'
services:
  database:
    container_name: friendship_api_development_database
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: friendship_api_development
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - friendship_api_development
volumes:
  database:
networks:
  friendship_api_development:
