version: '3.8'
name: 'friendship_api'
services:
  database:
    container_name: friendship_api_database
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: friendship_api
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - friendship_api
  api:
    container_name: friendship_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - database
    environment:
      PORT: 3000
      DATABASE_URL: 'postgres://root:root@database:5432/friendship_api?schema=public'
    networks:
      - friendship_api
volumes:
  database:
networks:
  friendship_api:
